frontendPublicHttpProtocol: 'http'
environment: 'prod'
externalHostNameUrl: ''
languages: ['en','cy']
TestOutputDir: './functional-output'
featureToggles:
  enabled: true
  launchDarklyKey: 'SDK_KEY'
  launchDarklyUser:
    firstName: 'Caveats'
    lastName: 'Frontend'
    key: 'LAUNCHDARKLY_USER_KEY'
  ft_caveats_shutter: 'probate-caveats-fe-shutter'
  ft_pcq: 'probate-caveats-pcq'
  ft_pcq_token: 'probate-caveats-pcq-token'
  ft_enable_webchat: 'probate-caveat-enable-webchat'
  ft_use_new_webchat: 'probate-use-new-webchat'
  appwideToggles: ['ft_enable_webchat', 'ft_use_new_webchat']
app:
  useHttps: 'false'
  port: '3000'
  useCSRFProtection: 'true'
  basePath: ''
health:
  service_name: 'Stop a grand of probate - caveats'
  timeout: 30000
  deadline: 30000
services:
  orchestrator:
    name: 'Orchestrator Service'
    url: 'http://localhost:8888'
    port: 8888
    paths:
      checkanswerspdf: 'documents/generate/checkAnswersSummary'
      payment_updates: '/payment-updates'
  idam:
    name: 'IdAM Service'
    apiUrl: 'http://localhost:5000'
    roles: ['probate-private-beta','citizen']
    s2s_url: 'http://localhost:4502'
    service_name: 'probate_frontend'
    service_key: 'AAAAAAAAAAAAAAAA'
    probate_oauth2_client: 'probate'
    probate_oauth2_secret: '123456'
    caveat_user_email: 'testusername@test.com'
    caveat_user_password: 'Pa55word11'
    caveat_redirect_base_url: 'http://localhost:3000'
    caveat_redirectUrl: '/oauth2/callback'
  pact:
    name: 'PACT Service'
    url: 'https://pact-broker.platform.hmcts.net'
    tag: 'Dev'
    pactDirectory: 'pacts'
  payment:
    name: 'Payment Service'
    createPaymentUrl: 'http://localhost:8383/card-payments'
    externalUrl: 'https://card.payments.service.gov.uk'
    authorization: 'dummy_token'
    serviceAuthorization: 'dummy_token'
    userId: 46
    returnUrlPath: '/payment-status'
  feesRegister:
    name: 'Fees Register Service'
    url: 'http://localhost:4411/fees-register'
    port: 4411
    paths:
      fees: '/fees'
      feesLookup: '/fees/lookup'
    ihtMinAmt: 5000
    caveat_newfee_data:
      applicant_type: 'all'
      channel: 'default'
      event: 'miscellaneous'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      keyword: 'Caveat'
      service: 'probate'
  postcode:
    name: 'Postcode Lookup Service'
    token: ''
  equalityAndDiversity:
    name: 'Equality and Diversity Service'
    url: 'http://localhost:4000'
    path: '/service-endpoint'
    port: 4000
    tokenKey: 'PROBATE_TOKEN_KEY'
redis:
  host: 'localhost'
  port: 6379
  password: 'dummy_password'
  useTLS: 'false'
  enabled: 'false'
  secret: 'OVERWRITE_THIS'
  proxy: true
  resave: false
  saveUninitialized: false
  cookie:
    secure: false
    httpOnly: true
    sameSite: 'lax'
dateFormat: 'DD/MM/YYYY'
payloadVersion: '4.1.0'
hostname: 'localhost:3000'
enableTracking: 'true'
webchat:
  avayaUrl: 'webchat.pp.ctsc.hmcts.net'
  avayaClientUrl: 'webchat-client.pp.ctsc.hmcts.net'
  avayaService: 'Testing'
  kerv:
    deploymentId:
      en: 'kerv-deployment-en'
      cy: 'kerv-deployment-cy'
    genesysBaseUrl: 'kerv-genesys-base-url'
    environment: 'kerv-environment'
    kervBaseUrl: 'kerv-kerv-base-url'
    apiKey: 'kerv-api-key'
links:
  accessibility: '/caveats/accessibility-statement'
  cookies: '/caveats/cookies'
  privacy: '/caveats/privacy-policy'
  terms: '/caveats/terms-conditions'
  contact: '/caveats/contact-us'
  avaya-webchat: '/caveats/avaya-webchat'
  callCharges: 'https://www.gov.uk/call-charges'
  howToManageCookies: 'https://www.aboutcookies.org'
  googlePrivacyPolicy: 'https://www.google.com/policies/privacy/partners/'
  googleAnalyticsOptOut: 'https://tools.google.com/dlpage/gaoptout/'
  mojPersonalInformationCharter: 'https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter'
  survey: 'https://www.smartsurvey.co.uk/s/Probate_Feedback/'
  surveyEndOfApplication: 'https://www.smartsurvey.co.uk/s/Probate_ExitSurvey/'
  applicationFormPA8A: 'https://www.gov.uk/government/publications/form-pa8a-caveat-application-form'
  myhmctsManageCasesLink: 'https://manage-case.platform.hmcts.net/'
  myhmctsRegisterLink: 'https://www.gov.uk/guidance/hmcts-online-services-for-legal-professionals'
  whoInheritsLink: 'https://www.gov.uk/inherits-someone-dies-without-will'
  citizenAdvice: 'https://www.citizensadvice.org.uk/'
  stopGrantOfRepresentation: 'https://www.gov.uk/wills-probate-inheritance/stopping-a-grant-of-representation'
  goodThingsFoundation: 'https://www.goodthingsfoundation.org'
  subjectAccessRequest: 'https://www.gov.uk/government/publications/request-your-personal-data-from-moj'
  complaintsProcedure: 'https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service/about/complaints-procedure'
  informationCommissionersOffice: 'https://ico.org.uk/global/contact-us'
  applicationFormPA15: 'https://www.gov.uk/government/publications/form-pa15-give-up-probate-executor-rights'
  deathReportedToCoroner: 'https://www.gov.uk/after-a-death/when-a-death-is-reported-to-a-coroner'
  hmctAccessAccessibilityStatement: 'https://hmcts-access.service.gov.uk/accessibility-statement'
  payAccessibilityStatement: 'https://www.payments.service.gov.uk/accessibility-statement/'
  notifyAccessibilityStatement: 'https://www.notifications.service.gov.uk/accessibility-statement'
  myAbilityLink: 'https://mcmw.abilitynet.org.uk/'
  equalityAdvisorLink: 'https://www.equalityadvisoryservice.com/'
  wcag21Link: 'https://www.w3.org/TR/WCAG21/'
  applyForCaveatFrontpage: 'https://www.apply-for-probate.service.gov.uk/caveats/start-apply'
  applyForCaveatFrontpageWelsh: 'https://www.apply-for-probate.service.gov.uk/caveats/start-apply?lng=cy'
  paymentsAccessibilityStatement: 'https://www.payments.service.gov.uk/accessibility-statement/'
utils:
  api:
    retries: 10
    retryDelay: 1000
    timeout: 30000
payment:
  applicationFee: 3
  applicationFeeThreshold: 5000
  serviceId: 'PROBATE'
  siteId: 'P223'
  currency: 'GBP'
appInsights:
  connectionString: ''
livenessEndpoint: '/health/liveness'
endpoints:
  health: '/health'
  info: '/info'
whitelistedPagesForStartApplyPageRedirect: [
  '/public',
  '/start-apply',
  '/bilingual-gop',
  '/applicant-name',
  '/accessibility-statement',
  '/cookies',
  '/privacy-policy',
  '/terms-conditions',
  '/contact-us',
  '/offline',
  '/health/liveness',
  '/avaya-webchat'
]
whiteListedPagesForThankyou: [
  '/public',
  '/accessibility-statement',
  '/cookies',
  '/privacy-policy',
  '/terms-conditions',
  '/contact-us',
  '/offline',
  '/health/liveness',
  '/thank-you',
  '/avaya-webchat'
]
whiteListedPagesForPaymentBreakdown: [
  '/public',
  '/accessibility-statement',
  '/cookies',
  '/privacy-policy',
  '/terms-conditions',
  '/contact-us',
  '/offline',
  '/health/liveness',
  '/payment-breakdown',
  '/payment-status',
  '/thank-you',
  '/avaya-webchat'
]

