featureToggles:
  enabled: true
  launchDarklyKey: 'sdk-4d50eb6e-8400-4aa7-b4c5-8bdfc8b1d844'
  launchDarklyUser:
    firstName: 'Probate'
    lastName: 'Frontend'
    key: '35222af3-7867-44ea-a2a0-f8e533ad12de'
  ft_fees_api: 'probate-fees-api'
  ft_pcq: 'probate-pcq'
  ft_pcq_token: 'probate-pcq-token'
  ft_avaya_webchat: 'probate-avaya-webchat'
  appwideToggles: ['ft_avaya_webchat']