TestFrontendUrl: 'http://localhost:3000'
TestE2EFrontendUrl: 'https://localhost:3000'
TestUseGovPay: 'false'
TestRetryFeatures: 3
TestRetryScenarios: 0
TestOutputDir: './functional-output'
TestPathToRun: './paths/**/*.js'
TestShowBrowser: false
TestBasePath: '/caveats'
postcodeLookup:
  contentType: 'application/json'
  singleAddressPostcode: 'SW1A 1AA'
  singleOrganisationName: 'BUCKINGHAM PALACE'
  singleFormattedAddress: 'Buckingham Palace\nLondon\nSW1A 1AA'
  multipleAddressPostcode: 'N145JY'
  partialAddressPostcode: 'N14'
  invalidAddressPostcode: 'Z99 9ZZ'
  emptyAddressPostcode: ''
govPayTestCardNos:
  validCardNo: '4242424242424242'
govPayTestCardDetails:
  expiryMonth: '06'
  expiryYear: '99'
  cardholderName: 'Test Payment'
  cvc: '123'
  addressLine1: '1'
  addressCity: 'London'
  addressPostcode: 'SW1A1AA'
validation:
  url: 'http://localhost:8080/validate'

TestGovUkConfirmPaymentUrl: 'www.payments.service.gov.uk'
TestEnvEmailAddress: 'masah.aspyn@sellcow.net'
TestEnvMobileNumber: '07545480473'
s2sStubErrorSequence: '000'
links:
  surveyEndOfApplication: 'https://www.smartsurvey.co.uk/'
  callCharges: 'https://www.gov.uk/call-charges'
  howToManageCookies: 'https://www.aboutcookies.org'
  googlePrivacyPolicy: 'https://www.google.com/policies/privacy/partners/'
  googleAnalyticsOptOut: 'https://tools.google.com/dlpage/gaoptout/'
  mojPersonalInformationCharter: 'https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter'
  goodThingsFoundation: 'https://www.goodthingsfoundation.org'
  subjectAccessRequest: 'https://www.gov.uk/government/publications/request-your-personal-data-from-moj'
  complaintsProcedure: 'https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service/about/complaints-procedure'
  informationCommissionersOffice: 'https://ico.org.uk/global/contact-us'
  ihtNotCompleted: 'https://www.gov.uk/valuing-estate-of-someone-who-died/tell-hmrc-estate-value'
  applicationFormPA15: 'https://www.gov.uk/government/publications/form-pa15-apply-for-renunciation-will'
helpline:
  number: '0300 303 0648'
  email: 'contactprobate@justice.gov.uk'
  hours: 'Monday to Friday 8:00am to 6:00pm. Saturday 8:00am to 2:00pm.'
pact:
  pactBrokerUrl: 'http://localhost:80'
featureToggles:
  enabled: false
