featureToggles:
  enabled: false
postcodeLookup:
  contentType: 'application/json'
  singleAddressPostcode: 'SW1A 1AA'
  singleOrganisationName: 'BUCKINGHAM PALACE'
  singleFormattedAddress: 'BUCKINGHAM PALACE, LONDON, SW1A 1AA'
  multipleAddressPostcode: 'N145JY'
  partialAddressPostcode: 'N14'
  invalidAddressPostcode: 'Z99 9ZZ'
  emptyAddressPostcode: ''
  token: ''
