nodejs:
  applicationPort: 3000
  environment:
    PUBLIC_PROTOCOL: https
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: probate-caveats-frontend
    FEATURE_TOGGLES_API_URL: http://${SERVICE_NAME}-ftr-tgl-api
    REFORM_ENVIRONMENT: aat
    USE_REDIS: true
    REDIS_USE_TLS: false
    REDIS_HOST: ${SERVICE_NAME}-redis-master
    REDIS_PORT: 6379
    USE_IDAM: true
    IDAM_SERVICE_KEY: ${IDAM_S2S_SECRET}
    IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_PROBATE: ${IDAM_SECRET_PROBATE}
    POSTCODE_SERVICE_URL: ${PRO_POSTCODE_SERVICE_URL}
    POSTCODE_SERVICE_TOKEN: ${PRO_POSTCODE_SERVICE_TOKEN}
    SURVEY: ${PRO_SURVEY}
    SURVEY_END_OF_APPLICATION: ${PRO_SURVEY_END_OF_APPLICATIONN}
    APPLICATION_FEE_CODE: ${PRO_APPLICATION_FEE_CODEL}
    UK_COPIES_FEE_CODE: ${PRO_UK_COPIES_FEE_CODE}
    OVERSEAS_COPIES_FEE_CODE: ${PRO_OVERSEAS_COPIES_FEE_CODE}
    SERVICE_ID: ${PRO_SERVICE_ID}
    SITE_ID: ${PRO_SITE_ID}

# Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

rpe-feature-toggle-api:
  releaseNameOverride: ${SERVICE_NAME}-ftr-tgl-api
  importer:
    cron:
      enabled: false
    oneoff:
      enabled: false
  java:
    releaseNameOverride: ${SERVICE_NAME}-ftr-tgl-api
    ingressIP: ${INGRESS_IP}
    consulIP: ${CONSUL_LB_IP}
    registerAdditionalDns:
      enabled: true
      primaryIngressHost: ${SERVICE_FQDN}
      prefix: ftr-tgl
    environment:
      FEATURES_DB_HOST: ${SERVICE_NAME}-ft-db
      ADMIN_USERNAME_TEST: admin@example.com
      ADMIN_PASSWORD_TEST: Password12
      EDITOR_USERNAME_TEST: editor@example.com
      EDITOR_PASSWORD_TEST: Password12
  postgresql:
    postgresqlDatabase: hmcts


redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
