apiVersion: v2
appVersion: "1.0"
description: A Helm chart for the HMCTS probate product
name: probate-caveats-fe
home: https://github.com/hmcts/probate-caveats-frontend
version: 2.3.5
dependencies:
  - name: nodejs
    version: 2.3.4
    repository: '@hmctspublic'
  - name: redis
    version: 10.6.18
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: idam-pr
    version: 2.2.6
    repository: '@hmctspublic'
    condition: idam-pr.enabled
